import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { FacebookIcon, TwitterIcon, PinterestIcon } from "react-share";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faInstagram,
  faFacebook,
  faPinterest,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";

export default function Home() {
  function FormkitArrowright() {
    return (
      <svg
        className="mt-auto"
        width="40px"
        height="40px"
        viewBox="0 0 16 9"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill="#FFFFFF"
          d="M12.5 5h-9c-.28 0-.5-.22-.5-.5s.22-.5.5-.5h9c.28 0 .5.22.5.5s-.22.5-.5.5Z"
        ></path>
        <path
          fill="#FFFFFF"
          d="M10 8.5a.47.47 0 0 1-.35-.15c-.2-.2-.2-.51 0-.71l3.15-3.15l-3.15-3.15c-.2-.2-.2-.51 0-.71c.2-.2.51-.2.71 0l3.5 3.5c.2.2.2.51 0 .71l-3.5 3.5c-.1.1-.23.15-.35.15Z"
        ></path>
      </svg>
    );

    function FormkitArrowleft() {
      return (
        <svg
          width="40px"
          height="40px"
          viewBox="0 0 16 9"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill="#000000"
            d="M12.5 5h-9c-.28 0-.5-.22-.5-.5s.22-.5.5-.5h9c.28 0 .5.22.5.5s-.22.5-.5.5Z"
          ></path>
          <path
            fill="#000000"
            d="M6 8.5a.47.47 0 0 1-.35-.15l-3.5-3.5c-.2-.2-.2-.51 0-.71L5.65.65c.2-.2.51-.2.71 0c.2.2.2.51 0 .71L3.21 4.51l3.15 3.15c.2.2.2.51 0 .71c-.1.1-.23.15-.35.15Z"
          ></path>
        </svg>
      );
    }
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-20 items-center justify-center bg-thrasker-header ">
        <Image
          src={"/logo.hq.png"}
          alt="second image"
          className=""
          width={131}
          height={39}
        />
      </div>
      <div>
        <div
          id="backgroundDiv"
          className="flex flex-col bg-black px-4 py-4 text-left text-2xl font-bold text-white md:px-20 md:py-16 md:text-6xl "
        >
          <div className="ml-4">
            <h1>Providing</h1>
            <h2 className="my-4">Commercial</h2>
            <h3>Technology Services</h3>
            <div className="w-full md:w-fit">
              <div className="flex flex-row items-center justify-center">
                <p className="mb-2 mt-4 text-xl  font-normal md:mt-12">
                  View all services
                </p>
                <FormkitArrowright />
              </div>
              <hr className="mt-2 w-full border border-white md:mt-4"></hr>
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-col justify-center px-4 pb-4 pt-8 text-left md:flex-row md:px-8 md:pb-12 md:pt-24">
        <div className="mx-auto mb-4 flex flex-col md:mb-0">
          <span className="mb-2 w-full text-xl md:mb-4 md:w-[300px] md:text-3xl">
            We Possess Exceptional Skill of The Highest Quality
          </span>
          <span className="text-thrasker-secondPage w-full md:w-[300px]">
            At Expedited Digital, we are your trusted partner for all your
            technology needs. Our managed IT services ensure smooth operations
            and our emergency solutions keep your business prepared.
          </span>
        </div>
        <Image
          src={"/macbooks.png"}
          alt="second image"
          className="mx-auto"
          width={238}
          height={269}
        />
      </div>

      <div
        id="secondDarkDiv"
        className="overflow-cli pb-12 overflow-clip bg-thrasker-header px-12 font-medium text-white"
      >
        <p className="mb-4 w-36 pt-12 text-left text-2xl">How We Do Business</p>
        <hr className="w-full border-2 border-white"></hr>
        <div className="flex flex-row">
          <div className="mr-auto mt-4 flex flex-col gap-[30%] text-3xl font-bold">
            <p>01</p>
            <p>02</p>
            <p>03</p>
          </div>
          <div className="mr-auto mt-4 flex flex-col gap-20 text-3xl font-bold">
            <div className="flex flex-col ">
              <p className="flex flex-row gap-4">
                <FormkitArrowright />
                Consult
              </p>
              <span className="text-thrasker-text w-72 text-lg font-normal">
                Start by reaching out to start the conversation.
              </span>
            </div>
            <div className="flex flex-col ">
              <p className="flex flex-row gap-4">
                <FormkitArrowright /> Design/Deploy
              </p>
              <span className="text-thrasker-text w-72 text-lg font-normal">
                Any job big or small, we&apos;ve got the tools and equipment.
              </span>
            </div>

            <div className="flex flex-col ">
              <p className="flex flex-row gap-4">
                <FormkitArrowright />
                Manage
              </p>
              <span className="text-thrasker-text w-72 text-lg font-normal">
                We take pride in performing our best, we can&apos;t wait to
                prove it.
              </span>
            </div>
          </div>
        </div>
      </div>

      <div id="iceCube" className="min-h-[50vh] bg-black px-12">
        <div className="flex h-full flex-row">
          <div className="z-10 mt-12 flex w-1/2 flex-col bg-transparent">
            <p className="my-4 font-semibold text-white">
              Our Mission is to provide unbeatable technology solutions that
              empower businesses to thrive in the digital era.
            </p>
            <span className="text-thrasker-textDarker mb-8">
              We are committed to delivering exceptional value through
              innovative services, competitive pricing, and unparalleled
              customer support. With our turnkey solutions and unwavering
              dedication, we strive to forge lasting partnerships and help
              businesses achieve their goals with the power of technology.
            </span>
          </div>
          <div className="relative h-full w-1/2 min-h-[50vh]">
            <Image
              layout="fill"
              src={"/iceCube.jpg"}
              alt="adobeStock"
              objectFit="cover"
              objectPosition="center"
            />
          </div>
        </div>
      </div>

      <div className="text-thrasker-textWhitePage px-12 py-8">
        <h1 className="text-thrasker-textWhitePage text-3xl font-medium">
          The Purpose
        </h1>
        <hr className="border-thrasker-textWhitePage mt-8 border-[1.5px]"></hr>

        <p className="text-md my-8 font-semibold">
          Our purpose is to make technology easier for our clients.
        </p>
        <span className="text-thrasker-secondPage">
          We believe that by simplifying complex technological solutions, we can
          create a seamless and exceptional experience for businesses. With our
          expertise and dedication to customer satisfaction, we strive to
          empower our clients to embrace the full potential of technology and
          achieve their goals with confidence. We are here to guide, support,
          and provide the tools that make technology work for you, so you can
          focus on what you do best – growing your business.
        </span>
        <Image
          src={"/laptop4k.jpg"}
          alt="secondAdobeStock"
          width={200}
          height={200}
          className="mb-16 mt-12 h-full w-full"
        />
        <div className="items-center justify-center text-center">
          <p className="my-4 text-center text-3xl">Today</p>
          <div className="inline-block">
            <div className="px-16">
              We are committed to continuous learning and embracing new
            </div>
            <div>
              technologies. By fostering personal connections with our peers,
              clients,
            </div>
            <div className="px-16">
              and suppliers, we stay at the forefront of advancements.
            </div>
          </div>
        </div>
      </div>

      <div id="footer" className=" text-thrasker-textFooter text-center">
        <div className="flex flex-row justify-center gap-4 pb-12 pt-16">
          <FontAwesomeIcon className="h-6 w-6 text-white" icon={faFacebook} />
          <FontAwesomeIcon className="h-6 w-6 text-white" icon={faTwitter} />
          <FontAwesomeIcon className="h-6 w-6 text-white" icon={faInstagram} />
          <FontAwesomeIcon className="h-6 w-6 text-white" icon={faPinterest} />
        </div>
        <div>
          <p className="mb-4">@2022 Expedited Digital.</p>
          <p>12094 Anderson Rd, Unit 119 Tampa, Florida, 33625 United States</p>
        </div>
        <p className="mt-12 flex flex-row items-center justify-center pb-12">
          You are subscribed to BlauMail Mailing List.
          <p className="underline">Unsubscribe</p>{" "}
        </p>
      </div>
    </>
  );
}
